#macro BEAT_DEFAULT_LISTENER_ORIENTATION [0, 0, 1000, 0, -1, 0]
#macro PHONIX_TICK_TIME 1/60*1000//in miliseconds
#macro PHONIX_DEFAULT_FALLOFF_REFERENCE 50
#macro PHONIX_DEFAULT_FALLOFF_MAX 100
#macro PHONIX_DEFAULT_FALLOFF_FACTOR 1